### ISSUE TITLE
질문있습니다!!

### ISSUE THREAD

**Issue by Hobeom** [joont92/joont92.github.io#2]
블로그글 보다가 레이아웃이 너무 이뻐서 들어왔습니다.
혹시 비슷하게 구현할 수 있는 글이나 레포가 있을까요??? :smile:

**Comment by junyoungpark92** [comment]
안녕하세용
이 블로그는 hexo 기반의 next 라는 테마를 사용하였습니다
<https://github.com/theme-next/hexo-theme-next> 여기를 참조하시면 됩니다~~ @Hobeam

**Comment by Hobeom** [comment]
빠른 답변 감사합니다 많은 도움이 되었습니다. 좋은하루 되세요 👍
